### ISSUE TITLE
[Bug]: Unable to deploy module with minimum configuration from docs due to missing grafana_api_key

### ISSUE THREAD

**Issue by jrbeilke** [aws-observability/terraform-aws-observability-accelerator#106]
### Welcome to the AWS Observability Accelerator

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues) and didn't find any.

### AWS Observability Accelerator Release version

v1.6.1

### What is your environment, configuration and the example used?

Terraform 1.1.9

EKS cluster deployed using AWS module:
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.5"

  cluster_name    = "core-dev"
  cluster_version = "1.24"
}
```

Attempting to deploy the terraform-aws-observability-accelerator using the minimum configuration from the documentation:
https://aws-observability.github.io/terraform-aws-observability-accelerator/concepts/
```
module "eks_observability_accelerator" {
  source = "github.com/aws-observability/terraform-aws-observability-accelerator"

  aws_region = "us-east-1"
  eks_cluster_id = module.eks.cluster_name
}
```

### What did you do and What did you see instead?

Terraform plan fails due to missing grafana_api_key:
```
╷
│ Error: Missing required argument
│
│   with module.eks_observability_accelerator.provider["registry.terraform.io/grafana/grafana"],
│   on .terraform/modules/eks_observability_accelerator/main.tf line 46, in provider "grafana":
│   46:   url  = local.amg_ws_endpoint
│
│ "url": all of `auth,url` must be specified
╵
╷
│ Error: Missing required argument
│
│   with module.eks_observability_accelerator.provider["registry.terraform.io/grafana/grafana"],
│   on .terraform/modules/eks_observability_accelerator/main.tf line 47, in provider "grafana":
│   47:   auth = var.grafana_api_key
│
│ "auth": one of `auth,cloud_api_key,oncall_access_token,sm_access_token` must be specified
╵
```

**Comment by vchintal** [comment]
@jrbeilke The documentation wasn't clear for me as well and I had been battling this for the past several hours. Go thru this blog post and everything starts to make sense: https://aws.amazon.com/blogs/mt/announcing-aws-observability-accelerator-to-configure-comprehensive-observability-for-amazon-eks/ 

It isn't as simple documentation makes it to be. There are some variables that are mandatory and must be provided. `grafana_api_key` being one of them. 

Good luck!

**Comment by bonclay7** [comment]
Thanks for opening this @jrbeilke, the docs needs more clarification. If you want to monitor your EKS cluster, follow this guide here https://aws-observability.github.io/terraform-aws-observability-accelerator/eks/
