### ISSUE TITLE
Data source with the same name already exists

### ISSUE THREAD

**Issue by nsathyan-aus** [aws-observability/terraform-aws-observability-accelerator#117]
#### Please describe your question here
I am getting following error when using my own managed grafana workspace Id. Any info on how to resolve this issue would be appreciated.

```
Error: status: 409, body: {"message":"data source with the same name already exists"}
│
│   with module.eks_observability_accelerator.grafana_data_source.amp,
│   on .terraform\modules\eks_observability_accelerator\main.tf line 50, in resource "grafana_data_source" "amp":
│   50: resource "grafana_data_source" "amp" {
```

#### Additional context
Here is my main.tf when encountered above error
```
module "eks_observability_accelerator" {
  source = "github.com/aws-observability/terraform-aws-observability-accelerator?ref=v1.5.0"

  aws_region     = var.aws_region
  eks_cluster_id = var.eks_cluster_id

  # deploys AWS Distro for OpenTelemetry operator into the cluster
  enable_amazon_eks_adot = true

  # reusing existing certificate manager? defaults to true
  enable_cert_manager = false

  # creates a new Amazon Managed Prometheus workspace, defaults to true
  enable_managed_prometheus = local.create_new_workspace

  # reusing existing Amazon Managed Prometheus if specified
  managed_prometheus_workspace_id     = var.managed_prometheus_workspace_id
  managed_prometheus_workspace_region = "us-east-1" # defaults to the current region, useful for cross region scenarios (same account)

  # sets up the Amazon Managed Prometheus alert manager at the workspace level
  enable_alertmanager = true

  # reusing existing Amazon Managed Grafana workspace
  enable_managed_grafana       = false
  managed_grafana_workspace_id = var.managed_grafana_workspace_id
  grafana_api_key              = var.grafana_api_key

  tags = local.tags
}
```

#### More

- [ ] Yes, I have checked the repo for existing issues before raising this question

**Comment by bonclay7** [comment]
Apparently you have a datasource in your managed grafana workspace called `aws-observabiliy-accelerator`, probably a previous deployment? 

If yes, are you trying to deploy multiple patterns (ex. java + eks monitoring)? and if yes, this will be fixed by https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/115

**Comment by nsathyan-aus** [comment]
I checked grafana workspace data sources and I do not see "aws-observability-accelearor' datasource. It is not a multiple pattern deployment.

![image](https://user-images.githubusercontent.com/98901384/219700425-85f85db4-a71b-4078-b338-742ab809f46f.png)

**Comment by bonclay7** [comment]
I meant inside the Grafana workspace . Also i can see that you don't have Managed Prometheus permissions attached to your Grafana workspace, that will be another issue
<img width="516" alt="image" src="https://user-images.githubusercontent.com/10175027/219721987-52dded46-d86b-49a8-bfb1-45322a1cc6f9.png">

**Comment by nsathyan-aus** [comment]
I deleted my grafana workspace and recreated new one. It resolved the above error. Thanks for your time.
