### ISSUE TITLE
Server is currently unable to handle the request

### ISSUE THREAD

**Issue by nsathyan-aus** [aws-observability/terraform-aws-observability-accelerator#119]
I am getting server is unable to handle the request. Is it because the identity under which terraform is running does not have permission to create the adot namespace?

```module.eks_observability_accelerator.module.operator[0].kubernetes_namespace_v1.adot: Creating...
module.eks_observability_accelerator.module.operator[0].kubernetes_cluster_role_binding_v1.adot: Creating...
╷
│ Error: the server is currently unable to handle the request (post namespaces)
│
│   with module.eks_observability_accelerator.module.operator[0].kubernetes_namespace_v1.adot,
│   on .terraform\modules\eks_observability_accelerator\modules\add-ons\adot-operator\main.tf line 9, in resource "kubernetes_namespace_v1" "adot":
│    9: resource "kubernetes_namespace_v1" "adot" {
│
╵
╷
│ Error: the server is currently unable to handle the request (post clusterrolebindings.rbac.authorization.k8s.io)
│
│   with module.eks_observability_accelerator.module.operator[0].kubernetes_cluster_role_binding_v1.adot,
│   on .terraform\modules\eks_observability_accelerator\modules\add-ons\adot-operator\main.tf line 265, in resource "kubernetes_cluster_role_binding_v1" "adot":
│  265: resource "kubernetes_cluster_role_binding_v1" "adot" {
```

**Comment by bonclay7** [comment]
This indeed looks like a permission issue. How did you created your cluster?

**Comment by nsathyan-aus** [comment]
We created using terraform template provided by AWS EKS blueprints. 
github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.23.0

**Comment by nsathyan-aus** [comment]
I noticed following API call is failing while deploying ADOT. I noticed it is using "localhost" as hostname when making an API call. How do I set cluster endpoint so that hostname can be set properly? Is there anything I am missing 


===========API Call =========================
POST /api/v1/namespaces HTTP/1.1
**Host: localhost**
User-Agent: HashiCorp/1.0 Terraform/1.3.7
Content-Length: 186
Accept: application/json, */*
Content-Type: application/json
Accept-Encoding: gzip
2023-02-21T19:38:06.910-0600 [DEBUG] provider.terraform-provider-kubernetes_v2.18.0_x5.exe:
{
 "kind": "Namespace",
 "apiVersion": "v1",
 "metadata": {
  "name": "opentelemetry-operator-system",
  "creationTimestamp": null,
  "labels": {
   "control-plane": "controller-manager"
  }
 },
 "spec": {},
 "status": {}
}


-----------------------------------------------------
[DEBUG] Kubernetes API Response Details:
---[ RESPONSE ]--------------------------------------
 HTTP/1.1 503 Service Unavailable
 Connection: close
 Content-Length: 326
 Content-Type: text/html; charset=us-ascii
 Date: Wed, 22 Feb 2023 01:38:07 GMT
 Server: Microsoft-HTTPAPI/2.0

 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
 <HTML><HEAD><TITLE>Service Unavailable</TITLE>
 <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
 <BODY><h2>Service Unavailable</h2>
 <hr><p>HTTP Error 503. The service is unavailable.</p>
 </BODY></HTML>

**Comment by nsathyan-aus** [comment]
This issue went away after consuming the latest version of the module. Closing the issue.
