### ISSUE TITLE
[FEATURE] Add logs and traces support for Amazon OpenSearch

### ISSUE THREAD

**Issue by awsdabra** [aws-observability/terraform-aws-observability-accelerator#125]
#### Is your feature request related to a problem? Please describe
Add logs and traces support for Amazon OpenSearch. Customers are looking for unified solutions capturing logs, metrics and traces.

#### Describe the solution you'd like
Add an example and relevant module to capture logs and traces support using FlurentBit, Data Prepper for Amazon OpenSearch. Customers are looking for unified solutions capturing logs, metrics and traces.

**Comment by bonclay7** [comment]
Nice!

**Comment by aalemanq** [comment]
Exist a way to overide config on this fluenbit to send opensearch with your custom config?
