### ISSUE TITLE
[FEATURE] Make Grafana folder and datasource creation configurable with boolean flags

### ISSUE THREAD

**Issue by vchintal** [aws-observability/terraform-aws-observability-accelerator#132]
#### Is your feature request related to a problem? Please describe
When trying to reuse the same repo with two EKS clusters, where two EKS clusters pipe their metrics to the same AMP workspace, the tasks would fail saying the Grafana folder and/or the datasource already exists. 

#### Describe the solution you'd like
I want to enable two boolean variables to control the creation of the Grafana folder and/or the datasource. When this repo is used for the first EKS cluster, the variables would be set to `true` and when run for the second EKS cluster they would be set to `false`

#### Describe alternatives you've considered
There aren't any suitable alternatives to the problem, other than the proposed solution above, in my opinion.

#### Additional context
Nope, that is all

**Comment by bonclay7** [comment]
Thanks for raising this @vchintal. Happy to review your PR when ready
