### ISSUE TITLE
[Bug]: Permission issue with the AWS One Observability Workshop

### ISSUE THREAD

**Issue by OverEngineerd** [aws-observability/terraform-aws-observability-accelerator#154]
### Welcome to the AWS Observability Accelerator

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues) and didn't find any.

### AWS Observability Accelerator Release version

v2.3.0

### What is your environment, configuration and the example used?

I'm using the `PetSite` infrastructure deployed as part of the [AWS One Observability Workshop](https://catalog.workshops.aws/observability/en-US). It comes as a one-click CloudFormation [deployment](https://catalog.workshops.aws/observability/en-US/installation/not-using-ee/deploy-app).

I also have a Cloud9 enviroment set up as per the workshop instructions and a [Grafana environment](https://catalog.workshops.aws/observability/en-US/aws-managed-oss/amg) created as well.

I'm using the [existing-cluster-with-base-and-infra](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/existing-cluster-with-base-and-infra) example.

### What did you do and What did you see instead?

After completing the set up for the existing-cluster-with-base-and-infra and running the `terraform apply` command, I got the following series of errors.
![image (11)](https://user-images.githubusercontent.com/17794069/232906248-98502084-5d81-4f28-b051-1b7df27e1872.png)

Reverting to tag `v2.2.0` results in a successful deployment and I'm able to access Grafana and view dashboards.

**Comment by bonclay7** [comment]
Hey @OverEngineerd sorry for the delay. First of all, make sure to authenticate with the same role that you used to create the cluster. There are couple of resources on the workshop that could conflict (ADOT collector, fluentBit), so maybe you'll need to cleanup. 
Try also have one instance more or bump slightly the instances types to have room for all the components that will be installed by the accelerator. 

--
Have you found a solution yet so far?
