### ISSUE TITLE
[Bug]: aws-for-fluentbit Fix logRetentionDays

### ISSUE THREAD

**Issue by ktibi** [aws-observability/terraform-aws-observability-accelerator#158]
### Welcome to the AWS Observability Accelerator

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues) and didn't find any.

### AWS Observability Accelerator Release version

2.3.0

### What is your environment, configuration and the example used?

Terraform v1.4.5
on windows_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0

Deploy on EKS 1.26

### What did you do and What did you see instead?

The name of value for the chart aws-for-fluent-bit for the retention in cloudwatchlog is 

```
cloudWatchLogs:
  .......
  logRetentionDays:
```

But in the terraform code (modules/eks-monitoring/add-ons/aws-for-fluentbit/values.yaml) we have :
`log_retention_days: ${log_retention_days}`

We need to replace by 
`logRetentionDays: ${log_retention_days}`

Also after test the Fix, we have error from the pod ( aws-for-fluent-bit ) : 
```
[2023/05/17 10:10:45] [error] [output:cloudwatch_logs:cloudwatch_logs.0] PutRetentionPolicy API responded with error='AccessDeniedException'
[2023/05/17 10:10:45] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to putRetentionPolicy
[2023/05/17 10:10:45] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Failed to send events
```
We need also to add PutRetentionPolicy in modules/eks-monitoring/add-ons/aws-for-fluentbit/data.tf

**Comment by bonclay7** [comment]
Thanks for opening this @ktibi

**Comment by bonclay7** [comment]
This should be fixed now, thanks again @ktibi
