### ISSUE TITLE
Otel configmap changes.

### ISSUE THREAD

**Issue by nsathyan-aus** [aws-observability/terraform-aws-observability-accelerator#161]
How to edit the configmap of the  adot-collector and make the pods to restart automatically? 

adot-collector is deployed as a daemonset. I made a change to one of the values in the configmap and restarted the daemonset.  I noticed that configmap still retained the old value and did not see it got updated to the new value and also noticed pods were not restarted because of this configmap change.  Am I missing anything here?  How do I force the configmap change and restart the pods?

I am trying to bump up the value of loglevel from Warn to Debug. My traces are not working and I really want to debug the collector. Right now, I am not getting any clue as why otel collector is not sending traces to x-ray exporter.  Need some pointers to help me debug this issue.

**Comment by ktibi** [comment]
You need to modify the custom ressource adot in opentelemetry.io/opentelemetrycollector
