### ISSUE TITLE
[FEATURE] Add curated kube-apiserver related Grafana dashboard 

### ISSUE THREAD

**Issue by youwalther65** [aws-observability/terraform-aws-observability-accelerator#190]
#### Is your feature request related to a problem? Please describe
kube-prometheus-stack comes by default with "kube-apiserver" Grafana dashboard. In our [AWS Observability Best Practices](https://aws-observability.github.io/observability-best-practices/guides/containers/oss/eks/best-practices-metrics-collection/#control-plane-metrics) and in other guides as well we recommend to monitor control plane metrics. But our AWS Observability Accelerator is missing a related Grafana dashboard

#### Describe the solution you'd like
I believe curated dashboard(s) containing available kube-apiserver and etcd metrics as described in [Control plane metrics with Prometheus](https://docs.aws.amazon.com/eks/latest/userguide/prometheus.html) from EKS docs should be added to AWS Observability Accelerator.
OTEL configuration already scrapes relevant metrics and importing a simple example kube-apiserver dashboard using those just worked.

#### Describe alternatives you've considered
Use kube-prometheus-stack instead of AWS Observability Accelerator. It already contains a **kube-apiserver** Grafana dashboard and all relevant scrape configs, recording rules etc.

**Comment by bonclay7** [comment]
@youwalther65 We've recently added the [EKS best practices recommended metrics](https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/185) and we'll add dashboards soon. kube-prometheus-stack dashboards have some additional data we are not able to scrape, so we'll need to curate a bit

**Comment by youwalther65** [comment]
@bonclay7 Sounds promising. I just saw the "kube-admin" scrape job which contains the kube-apiserver metrics to keep. This will need a slight adjustment if we are going to support EKS v1.26+ because metric `etcd_db_total_size_in_bytes` got renamed to to `apiserver_storage_db_total_size_in_bytes` starting with EKS 1.26, see source code [here ](https://github.com/kubernetes/apiserver/blob/release-1.26/pkg/storage/etcd3/metrics/metrics.go#L58-L66), these metrics are still Aplha. I already created an issue (and probably a PR soon) for [that](https://github.com/aws/aws-eks-best-practices/issues/345)

**Comment by youwalther65** [comment]
Implemented via PR [ Add Kubernetes admin dashboards #18 ](https://github.com/aws-observability/aws-observability-accelerator/pull/18) and [ Add Kubernetes admin dashboards for api-server #208 ](https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/208) in both related repos.

**Comment by youwalther65** [comment]
Merged and implement
