### ISSUE TITLE
[FEATURE] Migrating Alerting and Rules from Terraform code to GitOps approach

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/terraform-aws-observability-accelerator#193]
#### Is your feature request related to a problem? Please describe
This feature request is to migrate Alerting and Rules from Terraform code to GitOps approach. 

#### Describe the solution you'd like
This feature request is to migrate Alerting and Rules from Terraform code to GitOps approach. 

#### Describe alternatives you've considered
Use same as today in IaC

**Comment by bonclay7** [comment]
Thanks for this. I was thinking we could leverage AMP support for ACK for this https://aws.amazon.com/blogs/mt/introducing-the-ack-controller-for-amazon-managed-service-for-prometheus/

**Comment by elamaran11** [comment]
@bonclay7 We should deploy software/addons using IaC. And we should deploy configurations using GitOps. So i think we are doing good with what we have, we should move these configurations to GitOps. We are working on this for CDK already so we can do a joint effort.

**Comment by elamaran11** [comment]
@bonclay7 I think this is complete. Can we close this ticket?
