### ISSUE TITLE
Add a section that explains the opentelemetrycollector.yaml

### ISSUE THREAD

**Issue by SRJames** [aws-observability/terraform-aws-observability-accelerator#235]
It would be very useful if there was some information on how the collector.yaml file relates to the dashboards that are created.
As someone who is new to Prometheus and Grafana I have been struggling with which metrics are coming from which scrape_config.
This would be useful when trying to limit the amount of metrics that are being scraped.

**Comment by bonclay7** [comment]
Can you expand on which parts of the config you need help with?

**Comment by SRJames** [comment]
As a complete newcomer to Prometheus, Grafana and metrics, but using the repo due to following the AWS Observability Workshop, I think it would be useful to have some explanation of how the scrape_configs relate to the dashboards and possibly even explain what one or two of the configs are doing. By running with the full set you get a lot of nice dashboards but I then started to trim them down and attempt to reduce the amount of data being collected. I'm sure an experienced user would have little trouble, but as a novice this was quite a journey.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bonclay7** [comment]
Would something like this explanation help? https://catalog.workshops.aws/observability/en-US/aws-managed-oss/amp/ecs/ingest-custom#receivers

**Comment by bonclay7** [comment]
Also the upstream docs are really doing a good job on explaining the collector concepts 
https://opentelemetry.io/docs/collector/configuration/
