### ISSUE TITLE
Flux with own repo?

### ISSUE THREAD

**Issue by awsandy** [aws-observability/terraform-aws-observability-accelerator#236]
Hi

If I'm already using flux eg. bootstrapped with my own codecommit repo. How do I still use the observability accelerator which itself using flux with it's own repo ? (by default also in the flux-system namespace)

How can the two co-exist - or are you meant to install the observability accelerator, flux uninstall - and then bootstrap flux again with your own repo. ?

Thanks

**Comment by bonclay7** [comment]
In theory, it should be possible. Have you tried disable Flux install when using the module? https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/README.md#input_enable_fluxcd

You could the feed your parameters to your repo https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/README.md#input_flux_config

If there's anything to be added to fully support this, please let us knw
