### ISSUE TITLE
[FEATURE] Custom Service Account & IAM Role Names

### ISSUE THREAD

**Issue by aaguiar-2w** [aws-observability/terraform-aws-observability-accelerator#237]
The adot-operator forces a IAM role name convention that can lead to the IAM role name being more than 64 characters. Customization is limited to being able to define the service account name, but the otel-config submodule is hard coded to the default SA name

I want to update the otel-config helm chart to accept a custom service account name and update the eks-monitoring module to accept a custom IAM role name.

**Comment by bonclay7** [comment]
Thanks for opening this
