### ISSUE TITLE
[QUESTION] Do you accept a PR to add oltp exporters as an optional config

### ISSUE THREAD

**Issue by rlanore** [aws-observability/terraform-aws-observability-accelerator#240]
Hi,
I have a use case to send log,metrics and traces to another OpenTelemetry collector.

To do this i want to change exporters into opentelemetrycollector.yaml to oltp with endpoint and add extension like basicAuth

https://opentelemetry.io/blog/2022/k8s-otel-expose/

- [x] Yes, I have checked the repo for existing issues before raising this question

thks

**Comment by bonclay7** [comment]
If that's an option with a boolean flag, we could accept a PR. We are yet to add logs to the OTEL pipeline https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/247
