### ISSUE TITLE
All working ? but no data in Dashboards

### ISSUE THREAD

**Issue by awsandy** [aws-observability/terraform-aws-observability-accelerator#242]
Hi,

I have deployed the existing-cluster-with-base-and-infra example.

All seems to have deployed ok, deployments/statefulsets and pods are running.

In Grafana the dashboards have arrived and the aws-observability-accelerator "save and test" button says "data source is working" but there is "No data" on any of the dashboards.

Can you suggest any troubleshooting steps for this circumstance?

**Comment by bonclay7** [comment]
Check this one out, hope it helps https://aws-observability.github.io/terraform-aws-observability-accelerator/eks/troubleshooting/

**Comment by awsandy** [comment]
Hi,

Thanks for the pointer - In the end the problem was that the Role "grafana-assume" had no policies attached to it - as soon as I added the "AmazonPrometheusQueryAccess"  policy to this role - all the Grafana dashboards came to life.

I haven't explored as yet the root cause for this in the module code / my environment.

But it might be worth adding this check to the troubleshooting docs ?

Andy

**Comment by bonclay7** [comment]
Thanks for coming back and report. Absolutely! would you be up for a docs PR?
