### ISSUE TITLE
"unsupported protocol scheme" errors in the grafana operator

### ISSUE THREAD

**Issue by awsandy** [aws-observability/terraform-aws-observability-accelerator#271]
Hi, 

Been using this observability accelerator successfully in recent times, but now I'm getting  "unsupported protocol scheme" errors in the grafana operator (and no dashboards in Grafana)

kubectl logs grafana-operator-74d49bc4b4-pmk6k -n grafana-operator

2024-05-07T14:51:34Z    INFO    GrafanaDashboardReconciler      found matching Grafana instances for dashboard  {"controller": "grafanadashboard", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaDashboard", "GrafanaDashboard": {"name":"grafana-dashboards-kubeproxy","namespace":"grafana-operator"}, "namespace": "grafana-operator", "name": "grafana-dashboards-kubeproxy", "reconcileID": "fa0aab7a-be7d-405d-99e4-8f21b1f89f99", "count": 1}
2024-05-07T14:51:34Z    ERROR   GrafanaDashboardReconciler      error reconciling dashboard     {"controller": "grafanadashboard", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaDashboard", "GrafanaDashboard": {"name":"grafana-dashboards-kubeproxy","namespace":"grafana-operator"}, "namespace": "grafana-operator", "name": "grafana-dashboards-kubeproxy", "reconcileID": "fa0aab7a-be7d-405d-99e4-8f21b1f89f99", "dashboard": "grafana-dashboards-kubeproxy", "grafana": "external-grafana", "error": "Internal error occurred: Get \"g-45e90cf8de.grafana-workspace.eu-west-1.amazonaws.com/api/folders?limit=1000&page=1\": unsupported protocol scheme \"\""}
github.com/grafana-operator/grafana-operator/v5/controllers.(*GrafanaDashboardReconciler).Reconcile
        github.com/grafana-operator/grafana-operator/v5/controllers/dashboard_controller.go:257
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227

All the other troubleshooting steps give the expected output

Any suggestions ?

- [ ] Yes, I have checked the repo for existing issues before raising this question

**Comment by awsandy** [comment]
data "aws_grafana_workspace" "this" {
  workspace_id = data.aws_ssm_parameter.tf-eks-grafana-id.value
}


# eks 

module "eks_monitoring" {
  #depends_on = [aws_prometheus_workspace.amp-demo]
  source = "github.com/aws-observability/terraform-aws-observability-accelerator//modules/eks-monitoring"
  #source = "github.com/aws-observability/terraform-aws-observability-accelerator//modules/eks-monitoring?ref=v2.0.0"

  eks_cluster_id = data.aws_ssm_parameter.cluster-name.value


  #enable_fluxcd=false

  # deploys AWS Distro for OpenTelemetry operator into the cluster ! required
  enable_amazon_eks_adot = true

  # reusing existing certificate manager? set to false  defaults to true
  enable_cert_manager = true

  # enable EKS API server monitoring
  enable_apiserver_monitoring = true

  # deploys external-secrets in to the cluster
  enable_external_secrets = true
  grafana_api_key         = aws_grafana_workspace_api_key.key.key
  target_secret_name      = "grafana-admin-credentials"
  target_secret_namespace = "grafana-operator"
  grafana_url             = data.aws_grafana_workspace.this.endpoint


  # control the publishing of dashboards by specifying the boolean value for the variable 'enable_dashboards', default is 'true'
  enable_dashboards = true

  # creates a new Amazon Managed Prometheus workspace, defaults to true
  enable_managed_prometheus       = true

  # sets up the Amazon Managed Prometheus alert manager at the workspace level
  enable_alertmanager = true

  # optional, defaults to 60s interval and 15s timeout
  prometheus_config = {
    global_scrape_interval = "60s"
    global_scrape_timeout  = "15s"
  }


  # control the publishing of dashboards by specifying the boolean value for the variable 'enable_dashboards', default is 'true'
  #enable_dashboards = var.enable_dashboards
  #dashboards_folder_id            = module.aws_observability_accelerator.grafana_dashboards_folder_id

  enable_logs = true # logs for the observability accelerator itself (I think)
  enable_tracing = true

  #tags = local.tags

}


---------

$ terraform state show data.aws_grafana_workspace.this | grep endpoint
    endpoint                  = "g-45e90cf8de.grafana-workspace.eu-west-1.amazonaws.com"

**Comment by awsandy** [comment]
should the grafana_url begin with. https://g-xxx  ?

**Comment by awsandy** [comment]
yes it should - changed it to:

grafana_url             = format("https://%s",data.aws_grafana_workspace.this.endpoint)

and it worked - thanks for the hint.

**Comment by awsandy** [comment]
Thanks

**Comment by bonclay7** [comment]
Maybe we need to make this a bit more clear in the parameters' documentation. Thanks for confirming issue resolved
