### ISSUE TITLE
[Bug]: Cannot convert the confmap.Conf: environment variable "1" has invalid name

### ISSUE THREAD

**Issue by cloudchristina** [aws-observability/terraform-aws-observability-accelerator#279]
### Welcome to the AWS Observability Accelerator

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues) and didn't find any.

### AWS Observability Accelerator Release version

v2.12.0

### What is your environment, configuration and the example used?

Environment: EKS observability, EKS version 1.29.
EKS ADOT Add-on version: `v0.102.0`

Configuration: using [https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/[…]ks-monitoring/otel-config/templates/opentelemetrycollector.yaml](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml)

Example used: https://aws-observability.github.io/terraform-aws-observability-accelerator/eks/

### What did you do and What did you see instead?

I followed the instructions. 

Errors: `Error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA- ││`

![image](https://github.com/user-attachments/assets/cdc1b6f7-ff8c-4c30-be4e-9f2d249c9ffd)

Other:

I have tested with `v0.104.0`, `v0.107.0`, `v0.108.0` all same errors

otel **Chart.yml**
```
apiVersion: v2
name: opentelemetry
description: A Helm chart to install otel operator
type: application
version: 0.8.0
appVersion: 0.108.0

```
### Additional Information

Interesting things is I followed the instructions and deployed whole observability resources about 2 weeks ago and everything works fine.

**Comment by akhilv-ciq** [comment]
The issue is because of [this](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/71006497c3c575f68a1b1c84ceb4d693a5d9d096/modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml#L105) line.

Please change `replacement: $1` to `replacement: $$1`

**Comment by subhashvizio** [comment]
Ran into same issue. No more errors after replacing `$$1` with `$${1}` and `$$2` with `$${2}`
AWS have to make this fix in their [example](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml). Until then have to download the module and make the changes locally.

**Comment by bonclay7** [comment]
#281 should address this
