### ISSUE TITLE
Security - Update the stack to read all API keys from AWS Secrets Manager

### ISSUE THREAD

**Issue by satveerkhurpa** [aws-observability/terraform-aws-observability-accelerator#31]
#### Is your feature request related to a problem? Please describe
The Grafana API key is stored in .tf files and is not secure. All users will start cloning the repo and storing keys in .tf files that will be in public (cloned) repos. It will be good to update the stack to move the keys and any sensitive information into AWS Secrets Manager and read from there. The EKS and ECS Blueprints already follow this approach.

#### Describe the solution you'd like
Store API keys and secrets in AWS Secrets Manager and update the TF stack to read the value from AWS Secrets Manager.

**Comment by bonclay7** [comment]
Thanks @satveerkhurpa for raising this. We will provide an update to completely automate this process

**Comment by bonclay7** [comment]
@satveerkhurpa We have taken another approach with #33 to use control plane Managed Grafana API keys for now. It's on our roadmap to lift the API key restriction https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/24

**Comment by bonclay7** [comment]
Closing this for now.
