### ISSUE TITLE
add dashboard for K8

### ISSUE THREAD

**Issue by enghwa** [aws-observability/terraform-aws-observability-accelerator#36]

**Comment by bonclay7** [comment]
@enghwa can you clarify your ask for this? Have you taken a look at the `infra module` for EKS monitoring?
https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/existing-cluster-with-base-and-infra

**Comment by enghwa** [comment]
yes. i am using that for existing EKS cluster.. specifically this cluster is the target for airflow jobs.. and there are hundreds of pods that are fired by airflow DAG (https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html), but these pod metrics/lifetime are not tracked by the o11y dashboard.

**Comment by bonclay7** [comment]
Got it, so is this a duplicate of https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/37?

**Comment by bonclay7** [comment]
We will have a specific module for Airflow / batch jobs to get those metrics/dashboards

**Comment by enghwa** [comment]
yes.
