### ISSUE TITLE
[FEATURE] Optimize install time to take ~30s

### ISSUE THREAD

**Issue by ampabhi-aws** [aws-observability/terraform-aws-observability-accelerator#39]
#### Is your feature request related to a problem? Please describe
I'd like for the Observability Accelerator to be quicker to install. Right now it takes > 1-2 min to install, and ideally it would be great if it could be installed in 30s or less.

**Comment by bonclay7** [comment]
I would love to do that, we can see what can be done. However, Terraform only orchestrates resources creation/deletion. Most time spent is with the ADOT add-on, and I think this is out of scope here
