### ISSUE TITLE
[FEATURE] Cluster Infrastructure metrics - Node Metrics

### ISSUE THREAD

**Issue by ampabhi-aws** [aws-observability/terraform-aws-observability-accelerator#41]
#### Is your feature request related to a problem? Please describe
Thanks for putting this tool together! It packages some fantastic dashboards. However, I find it lacking in explaining node health.

#### Describe the solution you'd like
Could you provide OOTB dashboards for node CPU/MEM/Disk utilization? Standard infrastructure health metrics would help a Kubernetes operator monitor the health of their nodes.

#### Describe alternatives you've considered
Kube-prometheus-stack has some node / instance dashboards that I'm a big fan of. Would love to see if we can bring those into this project.

**Comment by awsvikram** [comment]
Dashboards have been successfully published in the PR #43
