### ISSUE TITLE
[FEATURE] Support for Terraform 1.3.0?

### ISSUE THREAD

**Issue by kaihendry** [aws-observability/terraform-aws-observability-accelerator#45]
#### Please describe your question here

Is there some specific reason you don't support the latest stable release of Terraform? https://github.com/hashicorp/terraform/releases/tag/v1.3.0

https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/versions.tf

#### More

- [X] Yes, I have checked the repo for existing issues before raising this question

**Comment by kaihendry** [comment]
Just ran into https://github.com/hashicorp/terraform/issues/31692

```╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/eks_observability_accelerator.operator.cert_manager/modules/irsa/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
```

Can't believe Terraform is engineered like this..

**Comment by bonclay7** [comment]
I will mark it as a feature request, but as you saw, there's a feature we are using that is not backwards compatible. We'll work on a fix
