### ISSUE TITLE
[Bug]: managed_grafana is empty tuple

### ISSUE THREAD

**Issue by kaihendry** [aws-observability/terraform-aws-observability-accelerator#47]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues) and didn't find any.

### Amazon EKS Blueprints Release version

3b1b530050db752d14657addfe6fcb7a60c743a8

### What is your environment, configuration and the example used?

Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/grafana/grafana v1.25.0
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/awscc v0.32.0
+ provider registry.terraform.io/hashicorp/helm v2.7.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1

Your version of Terraform is out of date! The latest version
is 1.3.1. You can update by downloading from https://www.terraform.io/downloads.html

### What did you do and What did you see instead?

```
(ins)[hendry@t14g3 existing-cluster-with-base-and-infra]$ cat terraform.tfvars
# (mandatory) AWS Region where your resources will be located
aws_region = "ap-southeast-1"

# (mandatory) EKS Cluster name
eks_cluster_id = "hello-eks"

# (optional) Leave it empty for a new workspace to be created
managed_prometheus_workspace_id = ""
(ins)[hendry@t14g3 existing-cluster-with-base-and-infra]$ terraform plan
data.aws_eks_cluster_auth.this: Reading...
data.aws_eks_cluster.this: Reading...
module.eks_observability_accelerator.data.aws_region.current: Reading...
data.aws_eks_cluster_auth.this: Read complete after 0s [id=hello-eks]
module.eks_observability_accelerator.data.aws_eks_cluster.eks_cluster: Reading...
module.eks_observability_accelerator.data.aws_partition.current: Reading...
module.eks_observability_accelerator.data.aws_caller_identity.current: Reading...
module.eks_observability_accelerator.data.aws_region.current: Read complete after 0s [id=ap-southeast-1]
module.eks_observability_accelerator.data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_eks_cluster.this: Read complete after 0s [id=hello-eks]
module.eks_observability_accelerator.data.aws_eks_cluster.eks_cluster: Read complete after 0s [id=hello-eks]
module.eks_observability_accelerator.module.operator[0].data.aws_eks_addon_version.this: Reading...
module.eks_observability_accelerator.module.operator[0].data.aws_eks_addon_version.this: Read complete after 1s [id=adot]
module.eks_observability_accelerator.data.aws_caller_identity.current: Read complete after 1s [id=160071257600]
module.eks_observability_accelerator.module.operator[0].module.cert_manager[0].data.aws_iam_policy_document.cert_manager_iam_policy_document: Reading...
module.eks_observability_accelerator.module.operator[0].module.cert_manager[0].data.aws_iam_policy_document.cert_manager_iam_policy_document: Read complete after 0s [id=2873133587]
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on .terraform/modules/eks_observability_accelerator.operator.cert_manager/modules/irsa/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and 3 more similar warnings elsewhere)
╵
╷
│ Error: Invalid index
│
│   on ../../locals.tf line 28, in locals:
│   28:   amg_ws_endpoint = var.managed_grafana_workspace_id == "" ? "https://${module.managed_grafana[0].workspace_endpoint}" : "https://${data.aws_grafana_workspace.this[0].endpoint}"
│     ├────────────────
│     │ module.managed_grafana is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

**Comment by bonclay7** [comment]
@kaihendry, do you have a managed grafana workspace and did you created the temporary API key?

**Comment by kaihendry** [comment]
I don't have a Grafana managed workspace. I don't quite understand how to proceed?

**Comment by bonclay7** [comment]
One of the requirements to run this example is to have one.
Normally this example can create a Grafana workspace for you. However there's a Terraform catch so you will have to run the example in multiple steps.

1. Create the workspace

Edit `main.tf` and set `enable_managed_grafana = true`

Create the workspace:
```console
terraform apply -var-file=dev.tfvars -target "module.eks_observability_accelerator.module.managed_grafana[0].aws_grafana_workspace.this[0]"
```
2. Run a second time the example with grafana workspace id filled (and API Key) following the instructions

3. To log in to Grafana you will have to setup SSO https://aws.amazon.com/blogs/mt/amazon-managed-grafana-getting-started/

--

I will log an issue to have an automated end-to-end example for this.

Terraform has two different providers for AWS and Grafana, evaluated at the same time, so there's a dependency issue we cannot resolve yet with the latest version of Terraform.

**Comment by kaihendry** [comment]
I'm hoping to use these blueprints as bootstrapping some EKS Observability in Jakarta.  All the services need to be in Jakarta, so I guess managed Grafana/Prom isn't gonna work.

**Comment by kaihendry** [comment]
I don't have time for waiting around. Waiting for MSK in Jakarta was torturous.

**Comment by bonclay7** [comment]
If you can have your EKS cluster in Jakarta and Managed Prometheus and Grafana running in Singapore for example, will that be ok?
Is there a specific reason why it has to be Jakarta?

**Comment by kaihendry** [comment]
It's need to be all in Jakarta for compliance reasons. I will just go for some Prom / Grafana operator for k8s and try pick up the pieces wrt Cloudwatch agent et al.

**Comment by bonclay7** [comment]
Thanks for raising the issue. I will close this for now. I think it would be very useful to request support for Jakarta in the roadmap projects I shared even if you are doing something else.
