### ISSUE TITLE
Cleaning Terraform Files under Clone root folder.

### ISSUE THREAD

**Issue by sunilsinghc** [aws-observability/terraform-aws-observability-accelerator#62]
When We clone the Git Repo we are getting unwanted terraform files in the root directory which needs to be cleaned up as it causes confusion. I ended up running terraform init and deplpy from wrong root directory instead of transversing to the correct examples location. 

Valid working terraform-aws-observability-accelerator terraform files and setup are under **https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples** 

If possible we can clean up below files which will prevent users from accidentally running terraform from wrong place.

=> ~/Observablity/**terraform-aws-observability-accelerator** =>ll *.tf
-rw-r--r--  1 sunilcsi  staff  2331 Nov  1 20:11 locals.tf
-rw-r--r--  1 sunilcsi  staff  1473 Nov  1 20:11 main.tf
-rw-r--r--  1 sunilcsi  staff  1194 Nov  1 20:11 outputs.tf
-rw-r--r--  1 sunilcsi  staff  1986 Nov  1 20:11 variables.tf
-rw-r--r--  1 sunilcsi  staff   314 Nov  1 20:11 versions.tf
11:26:32=> ~/Observablity/myfork/terraform-aws-observability-accelerator =>

**Comment by bonclay7** [comment]
The root folder represents the main module of this repo. Without them, you would not be able to run any example. This is actually common amongst terraform modules, see https://github.com/terraform-aws-modules/terraform-aws-vpc. 

Our examples are just one way to consume those modules.

```hcl
module "eks_observability_accelerator" {
  source = "github.com/aws-observability/terrarom-aws-observability-accelerator?ref=v1.4.0"
```

This snippet above actually use those files in the root folder
