### ISSUE TITLE
[FEATURE] GitOps approach to create Grafana Datasource and Grafana Dashboards on AMG.

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/terraform-aws-observability-accelerator#64]
#### Is your feature request related to a problem? Please describe
We can benefit from a GitOps approach to create Grafana Datasource and Grafana Dashboards from GitOps repo on remote AMG. We can also think about deploying Grafana Operator to achieve this.

#### Describe the solution you'd like
A GitOps approach to create Grafana Datasource and Grafana Dashboards from GitOps repo on remote AMG.  This will help customers to manage a Single repo to create Dashboards on same kind across multiple clusters. This Decouples the Grafana Dashboard work for Ops Personas from Cloud Infra personas who creates this accelarator infrastructure. Using GitOps approach helps customers who wants to run 100s and 1000s of clusters to create Grafana Dashs.

#### Describe alternatives you've considered
Grafana Operator

#### Additional context
https://github.com/grafana-operator/grafana-operator

**Comment by elamaran11** [comment]
Commenting to keep the ticket active.

**Comment by elamaran11** [comment]
Hello. Please keep this ticket open. This is an important feature we are working on for.

**Comment by elamaran11** [comment]
Commenting to keep the ticket active.

**Comment by bonclay7** [comment]
@elamaran11 Will extend the duration of closing tickets as some items like this one are planned to be done

**Comment by elamaran11** [comment]
This is not fuly complete. We still need to complete V2 which is GitOps repo to create Grafana Dashboards

**Comment by lewinkedrs** [comment]
Closing as per #151
