### ISSUE TITLE
[FEATURE] Pass grafana provider as parameter to module 

### ISSUE THREAD

**Issue by hjander** [aws-observability/terraform-aws-observability-accelerator#79]
#### Is your feature request related to a problem? Please describe
As the TF Grafana provider is defined inline instead of being passed as a parameter to the module, the module cannot be used with  TF depends_on 

```
│ Error: Module is incompatible with count, for_each, and depends_on
│ 
│   on main.tf line 184, in module "gitlab_runner_monitoring":
│  184:     module.autoscaling-eks.cluster_id
│ 
│ The module at
│ module.gitlab_runner_monitoring.module.eks_observability_accelerator is a
│ legacy module which contains its own local provider configurations, and so
│ calls to it may not use the count, for_each, or depends_on arguments.
│ 
│ If you also control the module
│ "git::https://github.com/aws-observability/terraform-aws-observability-accelerator.git?ref=tags/v1.5.0",
│ consider updating this module to instead expect provider configurations to
│ be passed by its caller.
```

#### Describe the solution you'd like
Pass the Grafana provider as parameter to the module.

#### Describe alternatives you've considered
-

#### Additional context
Using depends_on is necessary to ensure correct order in cluster with monitoring creation

**Comment by bonclay7** [comment]
@hjander can you explain a bit your use-case? I'd like to understand what you want to achieve
